[package]
name = "exec"
version = "0.1.0"
edition = "2021"
authors = ["grng3r <grng3r@protonmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
